aquasecurity/trivy-checks

rules/cloud/policies/aws/dynamodb/enable_at_rest_encryption.go
See https://github.com/aquasecurity/trivy/issues/5005
Encryption at rest is always [enabled](https://docs.aws.amazon.com/database-encryption-sdk/latest/devguide/client-server-side.html) for DynamoDB tables.
>DynamoDB transparently encrypts and decrypts all tables when they are written. There is no option to enable or disable encryption at rest.
=> fix(terraform): don't check encryption for DynamoDB tables in AVD-AWS-0023

rules/cloud/policies/aws/dynamodb/table_customer_key.go
1. DAX encryption [uses](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAXEncryptionAtRest.html) AWS KMS by default and this cannot be changed.
2. We should only check custom KMS if SSE is enabled otherwise AWS [uses](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-table-ssespecification.html) its own key.
=> fix(terraform): improve AVD-AWS-0025 rule

go.mod, go.sum, rules/cloud/policies/google/compute/enable_vpc_flow_logs.go, rules/cloud/policies/google/compute/enable_vpc_flow_logs_test.go
Proxy-only subnets don't support [VPC Flow Logs](https://cloud.google.com/vpc/docs/using-flow-logs).
Ref:
- https://cloud.google.com/load-balancing/docs/proxy-only-subnets#limitations
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_subnetwork#log_config
=> fix(google): do not check flow logs on proxy-only subnets

go.mod, go.sum, rules/cloud/policies/aws/cloudfront/use_secure_tls_policy.go, rules/cloud/policies/aws/cloudfront/use_secure_tls_policy_test.go
The user can set security policies (minimum_protocol_version) if `CloudFrontDefaultCertificate` is false and `SSLSupportMethod` is `sni-only`
Ref:
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesGeneral
Related PRs:
=> feat(aws): improve AVD-AWS-0013 rule

go.mod, go.sum, rules/cloud/policies/google/dns/no_rsa_sha1.go, rules/cloud/policies/google/dns/no_rsa_sha1.tf.go, rules/cloud/policies/google/dns/no_rsa_sha1_test.go
Fixed terraform examples and updated check due to schema change.
Related PRs:
- https://github.com/aquasecurity/defsec/pull/1496
=> fix(google): update AVD-GCP-0012 rule

checks/cloud/aws/iam/no_policy_wildcards.go, checks/cloud/aws/iam/no_policy_wildcards_test.go
ARNs that contain a wildcard in the object key are now allowed, as such an ARN has fewer object access privileges than an ARN that identifies all objects in the bucket. 
See https://github.com/aquasecurity/trivy/issues/5114
=> feat(aws): improve AVD-AWS-0057 rule

checks/cloud/digitalocean/compute/enforce_https.go, checks/cloud/digitalocean/compute/enforce_https_test.go, go.mod, go.sum
See https://github.com/aquasecurity/trivy/issues/5111
Now if `redirect_http_to_https` is enabled, the rule does not warn about using HTTP in the load balancer
=> feat(digitalocean): improve AVD-AWS-0012 rule

checks/kubernetes/general/runs_with_a_root_primary_or_supplementary_GID.rego, checks/kubernetes/general/runs_with_a_root_primary_or_supplementary_GID_test.rego
reported in https://github.com/aquasecurity/trivy/issues/4922 since the failRootGroupId rule is given a default value, it doesn't fail the deny rule and results in a false detection. added an explicit check for the failRootGropuId truthiness to resolve.
also fixed the sad path test
however I'm not sure how we're supposed to run the tests and if it's indeed broken
=> fix: fail for irrelevant resources

Makefile, checks/kubernetes/aquacommercial/configmap_with_sensitive.rego
Fixes the following issue
```shell
2024-01-13T14:25:34.160-0700    DEBUG   [misconf] 25:34.160914000 terraform.scanner.rego           Error occurred while parsing: Users/s/Library/Caches/trivy/policy/content/policies/kubernetes/policies/aquacommercial/configmap_with_sensitive.rego, Users/s/Library/Caches/trivy/policy/content/policies/kubernetes/policies/aquacommercial/configmap_with_sensitive.rego:96: rego_type_error: undefined ref: input.data[d]
input.data[d]
^
have: "data"
want (one of): ["apiVersion" "kind" "metadata" "rules" "spec"]
```
=> fix(checks): Use correct input for AVD-KSV-01010

Makefile
e339a0d removed the `test-rego` rule so references to it should also be removed.
=> fix: remove test-rego from Makefile

avd_docs/kubernetes/gke/AVD-KSV-01011/docs.md, checks/kubernetes/gke/authenticate_group_bind.rego, checks/kubernetes/gke/authenticate_group_bind_test.rego
Following to security risk raised on [system:authenticate ](https://orca.security/resources/blog/sys-all-google-kubernetes-engine-risk/) adding a new policy to handle this case
=> fix: add system authenticate bind protection policy

checks/docker/add_instead_of_copy.rego, checks/docker/add_instead_of_copy_test.rego
The reverse engineered `Dockerfile` of an image doesn't exactly match the original `Dockerfile`. For example, it doesn't have the original source files names. Instead, it uses `file:<hash> in`: `ADD file:8b8864b3e02a33a579dc216fd51b28a6047bc8eeaa03045b258980fe0cf7fcb3 in /__cacert_entrypoint.sh`
Such commands should not trigger AVD-DS-005.
=> fix(checks): handle `file:` and `multi:` in AVD-DS-005

checks/docker/copy_with_more_than_two_arguments_not_ending_with_slash.rego, checks/docker/copy_with_more_than_two_arguments_not_ending_with_slash_test.rego
The reverse engineered `Dockerfile` of an image doesn't exactly match
the original `Dockerfile`. For example, it doesn't have the original
source files names. Instead, it uses `file:<hash> in`:
`COPY file:8b8864b3e02a33a579dc216fd51b28a6047bc8eeaa03045b258980fe0cf7fcb3 in /__cacert_entrypoint.sh`
Such commands should not trigger AVD-DS-0011.
=> fix(checks): handle `file:` and `multi:` in AVD-DS-0011

checks/kubernetes/pss/baseline/11_seccomp_profile_unconfined.rego, checks/kubernetes/pss/baseline/11_seccomp_profile_unconfined_test.rego
Fixes https://github.com/aquasecurity/trivy/issues/4922
=> fix(checks): check the Seccomp of the controllers

.github/workflows/test-rego.yaml
OPA is required for the formatting check step
=> chore: restore the OPA installation

checks/kubernetes/gke/authenticate_group_bind.rego, checks/kubernetes/gke/authenticate_group_bind_test.rego
this change will:
1. apply policy on GKE cluster only
2. update policy severity to `CRITICAL`
- Related #65
=> fix: apply policy for gke provider only

checks/cloud/aws/cloudfront/use_secure_tls_policy.go, checks/cloud/aws/cloudfront/use_secure_tls_policy.tf.go, checks/cloud/aws/cloudfront/use_secure_tls_policy_test.go
SSLSupportMethod only restricts the minimum protocol version, so we don't need to check this.
Ref:
- https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ViewerCertificate.html
=> fix(aws): don't check SSLSupportMethod in AVD-AWS-0013

checks/kubernetes/pss/restricted/2_can_elevate_its_own_privileges.rego, checks/kubernetes/pss/restricted/2_can_elevate_its_own_privileges_test.rego
The rule was applied to all containers if at least one container had the `allowPrivilegeEscalation` parameter.
Fixes https://github.com/aquasecurity/trivy/issues/6232
=> fix(kubernetes): fix the KSV001 check

specs/compliance/docker-cis.yaml
The only relevant changes since 1.1.0 was the addition of 4.12: https://www.tenable.com/audits/items/CIS_Docker_v1.6.0_L1_Docker_Linux.audit:470a7effaa439e43f14af5e137c787d4
=> Update docker-cis benchmark to v1.6.0

checks/cloud/aws/iam/filter_iam_pass_role.rego
The page title for AVD-AWS-0342 in the vulnerability database documentation seems to be incorrect. The correct title is likely "Filter Passrole Access". I wasn't sure of the exact way to fix this, but I suspect that the issue might be related to the `short_code`. I have attempted to correct it accordingly.
https://avd.aquasec.com/misconfig/aws/iam/avd-aws-0342/
=> Fix page title for AVD-AWS-0342 in vulnerability database documentation

.github/workflows/release.yaml
These annotations are useful for tools (such as [Snyk uses them in its UI](https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/) and [Renovate uses them to find release notes](https://github.com/renovatebot/renovate/blob/34.115.1/lib/modules/datasource/docker/readme.md)) to use as well as for manual use by individuals.
See: https://github.com/opencontainers/image-spec/blob/v1.1.0/annotations.md#pre-defined-annotation-keys
[The trivy images at ghcr.io/aquasecurity/trivy and elsewhere already have OCI annotations.](https://github.com/aquasecurity/trivy/blob/7f8868b7d83fddf251ebe6a4d37f2482ae1e8a8a/goreleaser.yml#L127-L136)
=> Add OCI image annotations

checks/docker/update_instruction_alone.rego, checks/docker/update_instruction_alone_test.rego, checks/docker/yum_clean_all_missing.rego, checks/docker/yum_clean_all_missing_test.rego, lib/docker/docker.rego
Fixes a backwards compatibility violation for those who have not updated Trivy.
=> fix: use regex to split command

CONTRIBUTING.md, specs/compliance/aws-cis-1.2.yaml, specs/compliance/aws-cis-1.4.yaml, specs/compliance/docker-cis-1.6.0.yaml, specs/compliance/eks-cis-1.4.yaml, specs/compliance/k8s-cis-1.23.yaml, specs/compliance/k8s-nsa-1.0.yaml, specs/compliance/k8s-pss-baseline-0.1.yaml, specs/compliance/k8s-pss-restricted-0.1.yaml, specs/loader_test.go
feat: add compliance additional fields
- Related https://github.com/aquasecurity/trivy/issues/6602
=> feat: add compliance additional fields 

ARCHITECTURE.md, CONTRIBUTING.md, docs/compliance.md
docs: add compliance contribution docs
- Related https://github.com/aquasecurity/trivy/issues/6602
=> docs: add compliance contribution docs

avd_docs/aws/s3/AVD-AWS-0089/CloudFormation.md, avd_docs/aws/s3/AVD-AWS-0089/Terraform.md, cmd/avd_generator/main.go
A check may contain a few good or bad examples. But the `avd-generator` command generates only the first example.
=> fix(docs): generate multiple examples from Rego

scripts/testdata/main.tf, scripts/verify-bundle.go
Addresses: https://github.com/aquasecurity/trivy/issues/7031
=> test(bundle): Verify bundle usage

test/rules_test.go
In the process of migrating Go to Rego, checks may be duplicated. So deprecated Go checks can be omitted from the tests
=> test: exclude deprecated checks when detecting duplicates

.github/actions/setup-opa/action.yaml
Bumped up the OPA version to match the Go dependency version
=> ci: bump OPA to v0.65.0

.github/workflows/test-bundle.yml, .github/workflows/test-go.yaml, .github/workflows/test-rego.yaml, .github/workflows/verify-docs.yaml
Fixes the cache problem as in  https://github.com/aquasecurity/trivy-aws/pull/210 . The version in actions is bumped to 1.22 as in go.mod.
Before:
https://github.com/aquasecurity/trivy-checks/actions/runs/10385835515/job/28755821667
After:
https://github.com/aquasecurity/trivy-checks/actions/runs/10385999057/job/28756319104?pr=214
=> ci: pin Go version

checks/cloud/azure/network/no_public_ingress_test.go, internal/cidr/cidr.go, internal/cidr/cidr_test.go
Trivy doesn't detect any problem in the following Terraform file:
```terraform
resource "azurerm_network_security_group" "example" {
security_rule {
direction                  = "Inbound"
access                     = "Allow"
source_address_prefix      = "Internet"
}
}
```
Changing it to this, however, results in a critical finding:
```terraform
resource "azurerm_network_security_group" "example" {
security_rule {
direction                  = "Inbound"
access                     = "Allow"
source_address_prefix      = "internet"
}
}
```
Note the different casing of the `source_address_prefix`.
I've adjusted the CIDR checks to include the wildcards regardless of their casing. `internet` and `Internet` should now be treated the same way.
=> Ignore casing in CIDR wildcards

.github/actions/setup-opa/action.yaml, .github/workflows/outdated-api-update.yaml, .github/workflows/test-rego.yaml, Makefile, cmd/opa/main.go
While writing Rego checks, I encountered an [error](https://github.com/aquasecurity/trivy-checks/actions/runs/10483588564/job/29036542565) of using an undefined function when inspecting our bundle. This is because we use custom functions in Rego checks, so we have to use the OPA binary we build with these functions.  I think it is a bug that the error was not detected before. https://github.com/open-policy-agent/opa/issues/6946
=> ci: use OPA with custom built-in functions

scripts/verify-bundle.go
Some tests contain custom Rego functions that we recently added, which the latest version of Trivy (published in the docker) does not support. This is temporary until a new version of Trivy is released.
=> test(bundle): use only canary Trivy

avd_docs/aws/ecr/AVD-AWS-0031/docs.md, checks/cloud/aws/ecr/enforce_immutable_repository.go
I'm not sure if this is the correct location -- the same string seemed to show up in many different repos, but this seemed plausible.  If this should be in another location, let me know.  (This seemed to have the most complete information, including `<code>` tags...)
=> Fix typo in enforce_immutable_repository

checks/cloud/aws/iam/no_policy_wildcards.go, checks/cloud/aws/iam/require_support_role.go, checks/cloud/aws/sam/no_function_policy_wildcards.go, checks/cloud/aws/sam/no_state_machine_policy_wildcards.go, checks/cloud/aws/ssm/avoid_leaks_via_http.go
1. [AVD-AWS-0134](https://github.com/aquasecurity/trivy-checks/blob/main/checks/cloud/aws/ssm/avoid_leaks_via_http.go#L13). This check uses a mechanism of custom checks, which are passed terraform blocks directly rather than general state. Because of this, this check cannot be ported to Rego.
2. [AVD-AWS-0175](https://github.com/aquasecurity/trivy-checks/blob/main/checks/cloud/aws/accessanalyzer/enable_access_analyzer.go) and [AVD-AWS-0169](https://github.com/aquasecurity/trivy-checks/blob/main/checks/cloud/aws/iam/require_support_role.go). These checks are triggered when there are no resources. The problem is that Trivy does not export empty structures for Rego. Because of this, filtering with selectors does not work and the check is not applied. If you remove the selectors, the check …
=> chore(checks): deprecate some checks

checks/cloud/aws/cloudtrail/enable_all_regions.rego, checks/cloud/aws/cloudtrail/ensure_cloudwatch_integration.rego, checks/cloud/aws/cloudtrail/no_public_log_access.rego, checks/cloud/aws/cloudtrail/require_bucket_access_logging.rego, checks/cloud/aws/ec2/no_public_ingress_sgr.rego, checks/cloud/aws/iam/limit_root_account_usage.rego, checks/cloud/aws/iam/no_password_reuse.rego, checks/cloud/aws/iam/no_root_access_keys.rego, checks/cloud/aws/iam/no_user_attached_policies.rego, checks/cloud/aws/iam/require_lowercase_in_passwords.rego, checks/cloud/aws/iam/require_numbers_in_passwords.rego, checks/cloud/aws/iam/require_symbols_in_passwords.rego, checks/cloud/aws/iam/require_uppercase_in_passwords.rego, checks/cloud/aws/iam/set_max_password_age.rego, checks/cloud/aws/iam/set_minimum_password_length.rego
The default frameworks that Go checks have were missed in the migration.
=> checks: add default framework to some Rego checks

lib/cloud/aws_trails.rego, lib/docker/docker.rego
Fixes: https://github.com/aquasecurity/trivy/issues/7426
=> chore: mark Rego libs as libs

checks/kubernetes/cisbenchmarks/apiserver/encryption_provider_config.rego, checks/kubernetes/cisbenchmarks/apiserver/encryption_provider_config_test.rego
We found an incorrect rego-expression when checking the parameter --encryption-provider-config
=> fix(checks): invert logic of AVD-KCV-0030

avd_docs/aws/s3/AVD-AWS-0089/docs.md, checks/cloud/aws/s3/enable_logging.rego, checks/cloud/aws/s3/enable_logging_test.rego
Related Issues:
- Fixes https://github.com/aquasecurity/trivy/issues/7239
Related PRs:
- https://github.com/aquasecurity/trivy/pull/7284
=> feat(checks): improve S3 server logging access detection for AVD-AWS-0089

lib/cloud/metadata.rego, lib/cloud/metadata_test.rego
Ideally, we should point to the location of the misconfiguration in the code as precisely as possible. To do this, the `result.new` funuction takes an object with its location metadata as the second parameter. But there may be problems with this if the passed input is incomplete. 
The following check safely checks for the absence of `bar` or its false value, but may fail if `bar` or the parent structure is missing, since the `input.provider.foo.bar` expression passed to the `result.new` function will be `undefined`. 
```rego
deny contains res if {
not nput.provider.some_resource.block1.block2.some_attr.value
result.new(
"bar does not exist",
nput.provider.some_resource.block1.block2.some_attr,
)
}
```
To solve this problem, we could use the `object.get` function to safely get a nested …
=> feat: add function to retrieve object by path

avd_docs/aws/ec2/AVD-AWS-0105/CloudFormation.md, avd_docs/aws/ec2/AVD-AWS-0105/Terraform.md, avd_docs/aws/ec2/AVD-AWS-0105/docs.md, avd_docs/aws/ec2/AVD-AWS-0107/CloudFormation.md, avd_docs/aws/ec2/AVD-AWS-0107/Terraform.md, avd_docs/aws/ec2/AVD-AWS-0107/docs.md, checks/cloud/aws/ec2/no_public_ingress_acl.rego, checks/cloud/aws/ec2/no_public_ingress_acl_test.rego, checks/cloud/aws/ec2/no_public_ingress_sgr.rego, checks/cloud/aws/ec2/no_public_ingress_sgr_test.rego, lib/cloud/net.rego, pkg/specs/compliance/aws-cis-1.2.yaml, pkg/specs/compliance/aws-cis-1.4.yaml, test/rego/aws_ec2_test.go
This PR includes alignment of `AVD-AWS-0107` and `AVD-AWS-0105` checks with AWS CIS benchmarks v1.2 and v1.4.
Before: The check is triggered if a CIDR defines more than one public IP
Now: The check is triggered if the rule contains a CIDR that defines all available IP addresses, and uses TCP or UDP protocols for SSH or RDP ports.
Severity changed from `CRITICAL` to `HIGH`.
Ref:
- https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-13
- https://docs.aws.amazon.com/securityhub/latest/userguide/ec2-controls.html#ec2-14
Before: The check is triggered if a CIDR defines more than one public IP
Now: The check is triggered if the rule contains a CIDR that defines all available IP addresses and uses the TCP protocol for SSH or RDP ports. Severity changed from `CRITICAL` …
=> fix(checks): align AVD-AWS-0107 and AVD-AWS-0105 checks with CIS Benchmarks

checks/cloud/azure/network/disable_rdp_from_internet.rego, checks/cloud/azure/network/disable_rdp_from_internet_test.rego, checks/cloud/azure/network/ssh_blocked_from_internet.rego, checks/cloud/azure/network/ssh_blocked_from_internet_test.rego, test/rego/azure_network_test.go
Fixes: https://github.com/aquasecurity/trivy/issues/7681
=> fix(azure): properly check ports in AVD-AZU-0058 and AVD-AZU-0050

checks/cloud/nifcloud/computing/no_public_ingress_sgr.rego
The nifcloud computing rules were migrated to Rego at #185, but I found a difference with original Go rule.
Go: https://github.com/aquasecurity/trivy-checks/blob/v1.1.0/checks/cloud/nifcloud/computing/no_public_ingress_sgr.go#L40
```go
if cidr.IsPublic(rule.CIDR.Value()) && cidr.CountAddresses(rule.CIDR.Value()) > 1 {
```
Rego: https://github.com/aquasecurity/trivy-checks/blob/v1.1.0/checks/cloud/nifcloud/computing/no_public_ingress_sgr.rego#L39
```rego
cidr.is_public(rule.cidr.value)
cidr.count_addresses(rule.cidr.value) > 0
```
In Golang, it was an error if the address count was more than 1 (`> 1`), But in Rego, it is an error if the count is greater than 0 (`> 0`).  
I think it is correct to follow the Go code and use `> 1` as the condition.
=> fix(checks): correctly check the addresses count in the AVD-NIF-0001 rule

.github/workflows/release.yaml, scripts/verify-bundle.go
I could not copy `trivy-checks` into Harbor today because Harbor does not understand a `"size":0` manifest config.
The OCI image spec calls out this case and recommends sending an empty JSON object instead: https://github.com/opencontainers/image-spec/blob/v1.1.0/manifest.md#guidance-for-an-empty-descriptor
ORAS knows what to do with these things, so this change uses it the same way as `trivy-db`: https://github.com/aquasecurity/trivy-db/blob/32c63a9af03ffd449a6ffb4471745b6ec9714875/.github/workflows/cron.yml#L73
```
./oras push --artifact-type application/vnd.aquasec.trivy.config.v1+json \
```
Here's a discussion about the OPA bundle format showing similar: https://github.com/open-policy-agent/opa/issues/1413#issuecomment-491624560
```json
"config": {
"mediaType": …
```
=> Produce a manifest with a non-zero config

avd_docs/dockerfile/general/AVD-DS-0031/docs.md, checks/docker/README.md, checks/docker/leaked_secrets.rego, checks/docker/leaked_secrets_test.rego, cmd/id/main.go, lib/docker/path.rego
Close https://github.com/aquasecurity/trivy/issues/7639
The check is triggered in the following cases:
1. Using a secret environment variable in the argument (ARG) or environment variable (ENV).
Dockerfile:
```Dockerfile
FROM alpine
ARG GITHUB_TOKEN
```
Output:
```bash
CRITICAL: Possible exposure of secret env "GITHUB_TOKEN" in ARG
═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Passing secrets via `build-args` or envs or copying secret files can leak them out
See https://avd.aquasec.com/misconfig/ds031
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Dockerfile:4
────────────────────────────────────────────────────────────────────────────────────────── …
```
=> feat(checks): add secrets leak check in Dockerfile

avd_docs/kubernetes/general/AVD-KSV-0117/docs.md, checks/kubernetes/pss/baseline/12_privileged_ports_binding.rego
Fixes: https://github.com/aquasecurity/trivy/issues/7737
The [PR](https://github.com/kubernetes/kubernetes/issues/102612) for changing privileged ports has not been merged yet, so for now we downgrade the severity level from `High` to `Medium` according to the benchmark https://www.stigviewer.com/stig/kubernetes/2022-12-02/finding/V-242414 .
=> fix(k8s): downgrade KSV117 severity from High to Medium

checks/kubernetes/README.md, checks/kubernetes/cisbenchmarks/apiserver/security_context_deny_plugin.rego
Close: https://github.com/aquasecurity/trivy/issues/5541
=> feat(checks): Deprecate remaining PSP checks

checks/docker/add_instead_of_copy.rego, checks/docker/add_instead_of_copy_test.rego
`COPY` should be preferred over `ADD` when simply copying a file from the build context to the container. However, `ADD` supports additional features such as fetching files from remote HTTP(S) and Git URLS and extracting tar files.
See https://docs.docker.com/build/building/best-practices/#add-or-copy, https://github.com/aquasecurity/trivy/issues/7806 and https://github.com/aquasecurity/trivy/discussions/7791.
=> Allow the ADD instruction with HTTP, HTTPS and Git URLs

checks/docker/leaked_secrets.rego
Rule names must not start with `deny` or else they will be used as a result. https://github.com/aquasecurity/trivy/blob/main/pkg/iac/rego/scanner.go#L390
=> fix: do not use deny in rule name

scripts/verify-bundle.go
Merge once Trivy v0.57.0 is released.
This reverts commit b9b40904c9b0e217aa8f7238a473ca3b006bff09.
This is due to: https://github.com/aquasecurity/trivy/issues/7314
=> Revert "test(bundle): Disable canary builds"

lib/cloud/metadata.rego, lib/cloud/metadata_test.rego
IaC types have metadata in flat form next to the value
=> fix: fix metadata retrieval from iac types

test/docker_test.go, test/kubernetes_test.go
Related PRs:
- https://github.com/aquasecurity/trivy-checks/pull/282
=> test: unify docker and k8s tests

.github/workflows/release.yaml
This PR adds a checks bundle release to Docker Hub to allow the use of [mirror.gcr.io](https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images).
Test run of the action: https://github.com/nikpivkin/trivy-checks/actions/runs/11852006001/job/33029492752
Image: https://hub.docker.com/repository/docker/nikpivkin/trivy-checks/general
The action requires the `DOCKERHUB_USER` and `DOCKERHUB_TOKEN` secrets and create a `trivy-checks` repository on Docker Hub.
The variables `GHCR_USER` and `DOCKERHUB_REPOSITORY` are added to run an action in the fork. The defaults are `aqua-bot` and `aquasec` respectively.
Use of a mirror:
```bash
trivy conf main.tf -d --cache-dir cache --checks-bundle-repository mirror.gcr.io/nikpivkin/trivy-checks:latest
2024-11-15T13:35:32+06:00       DEBUG …
```
=> ci: push bundle to Docker Hub registry

scripts/verify-bundle.go
I recently migrated to the [colima](https://github.com/abiosoft/colima) container runtime and ran into the problem of running a test for a bundle:
```bash
2024/11/13 13:42:57 🚧 Waiting for container id 903598b9eaf7 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/11/13 13:42:57 failed accessing container logs: Error response from daemon: No such container: 903598b9eaf774df6452fe0c3d277731915c9a6d41730c3a83fa73e5bd4c99fd
panic: unexpected container status "removing": could not start container: creating reaper failed: failed to create container
goroutine 1 [running]:
main.createRegistryContainer({0x1055697c0, 0x1058aff20})
/Users/nikita/projects/trivy-policies/scripts/verify-bundle.go:32 +0x1d8
main.LoadAndVerifyBundle() …
```
=> chore: disable ryuk

Makefile
The command must match the [command](https://github.com/aquasecurity/trivy-checks/blob/main/.github/workflows/release.yaml#L35-L41) in the release, otherwise the config digest will be different.
=> chore: update push-bundle command

checks/cloud/aws/ec2/add_description_to_security_group_rule.rego, checks/cloud/aws/elasticache/add_description_for_security_group.rego, checks/cloud/aws/redshift/add_description_to_security_group.rego, checks/cloud/nifcloud/computing/add_description_to_security_group.rego, checks/cloud/nifcloud/computing/add_description_to_security_group_rule.rego, checks/cloud/nifcloud/nas/add_description_to_nas_security_group.rego, checks/cloud/nifcloud/rdb/add_description_to_db_security_group.rego, checks/cloud/openstack/networking/add_description_to_security_group.rego
This PR fixes the checks related to security groups so that they do not trigger on dummy resources. Trivy creates dummy resources to store orphan resources, i.e. without parent resources. For example, if no related `aws_security_group_rule` resources are found for `aws_security_group` resources, Trivy will create a dummy group to store the rules. 
- https://github.com/aquasecurity/trivy/issues/8054
=> fix checks related to security groups

checks/kubernetes/pss/baseline/11_seccomp_profile_unconfined.rego
We should only use objects as causes in kubernetes checks , since only they contain the locations used to display the findings.
Config:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
name: hello-sysctls
spec:
containers:
- name: hello
image: busybox
command:
- sh
- "-c"
- echo 'Hello' && sleep 1h
securityContext:
seccompProfile:
type: Unconfined
```
```bash
AVD-KSV-0104 (MEDIUM): container "hello" of pod "hello-sysctls" in "default" namespace should specify a seccomp profile
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
A program inside the container can bypass Seccomp protection policies.
See https://avd.aquasec.com/misconfig/ksv104 …
```
=> fix: use container as cause in KSV104 check

.github/workflows/test-rego.yaml, .regal/config.yaml, .regal/rules/custom/regal/rules/naming/deny-rule/deny_rule.rego, .regal/rules/custom/regal/rules/naming/deny-rule/deny_rule_test.rego, Makefile
This PR adds linting for Rego with two rules:
1. Only allow the following package namespaces, otherwise the check will be ignored by Trivy: `builtin,lib,defsec,appshield`.
2. Disallowing rules whose names start with `deny_` to avoid the problems described in [this PR](https://github.com/aquasecurity/trivy-checks/pull/283).
=> ci: init Rego linting

.github/workflows/test-rego.yaml, Makefile
I get the following warnings when running `fmt-rego` with OPA v1.0.0 on my machine:
```bash
❯ make fmt-rego
opa fmt -w lib/ checks/ examples/
failed to format Rego source file: 25 errors occurred:
lib/docker/docker.rego:9: rego_parse_error: `if` keyword is required before rule body
lib/docker/docker.rego:9: rego_parse_error: `contains` keyword is required for partial set rules
lib/docker/docker.rego:14: rego_parse_error: `if` keyword is required before rule body
lib/docker/docker.rego:14: rego_parse_error: `contains` keyword is required for partial set rules
lib/docker/docker.rego:19: rego_parse_error: `if` keyword is required before rule body
lib/docker/docker.rego:19: rego_parse_error: `contains` keyword is required for partial set rules
```
So we should use our custom OPA with the …
=> ci: use custom OPA to format Rego

checks/kubernetes/general/runs_with_GID_le_10000_test.rego, checks/kubernetes/general/runs_with_UID_le_10000_test.rego, checks/kubernetes/pss/restricted/5_runtime_default_seccomp_profile_not_set_test.rego, lib/kubernetes/kubernetes.rego, lib/kubernetes/kubernetes_test.rego, lib/kubernetes/security_context.rego
Fixes: https://github.com/aquasecurity/trivy/issues/8210
`SecurityContext` may inherit some fields from `PodSecurityContext`. See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#securitycontext-v1-core
Before:
```bash
❯ trivy conf test.yaml
2025-01-14T16:15:39+06:00       INFO    [misconfig] Misconfiguration scanning is enabled
2025-01-14T16:15:43+06:00       INFO    Detected config files   num=1
test.yaml (kubernetes)
Tests: 93 (SUCCESSES: 91, FAILURES: 2)
Failures: 2 (UNKNOWN: 0, LOW: 2, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
AVD-KSV-0020 (LOW): Container 'sec-ctx-demo' of Pod 'security-context-demo' should set 'securityContext.runAsUser' > 10000
════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════ …
```
=> fix(checks): respect PodSecurityContext for containers

checks/kubernetes/pss/restricted/5_runtime_default_seccomp_profile_not_set.rego, checks/kubernetes/pss/restricted/5_runtime_default_seccomp_profile_not_set_test.rego
Related PRs:
- https://github.com/aquasecurity/trivy-checks/pull/315
The current implementation in KSV030 uses 4 rules to validate the Seccomp profile (1 for the annotation and 3 for the securityContext) because the SecurityContext of the container does not inherit values from the PodSecurityContext. This makes it difficult to support check. [This](https://github.com/aquasecurity/trivy-checks/pull/315) PR adds inheritance of certain fields from the PodSecurityContext, including `seccompProfile.type`. With this, we can reduce the number of rules to 2, covering all possible cases:
1. Checking the pod annotation - to support older versions of Kubernetes.
2. Checking the securityContext of the container - for newer versions of Kubernetes.
=> fix(checks): dedupe KSV030 results

avd_docs/azure/network/AVD-AZU-0047/docs.md, avd_docs/azure/network/AVD-AZU-0051/docs.md, avd_docs/digitalocean/compute/AVD-DIG-0001/docs.md, avd_docs/digitalocean/compute/AVD-DIG-0003/docs.md, avd_docs/google/compute/AVD-GCP-0027/docs.md, avd_docs/google/compute/AVD-GCP-0035/docs.md, avd_docs/kubernetes/network/AVD-KUBE-0001/docs.md, avd_docs/nifcloud/computing/AVD-NIF-0001/docs.md, avd_docs/nifcloud/nas/AVD-NIF-0014/docs.md, avd_docs/nifcloud/rdb/AVD-NIF-0011/docs.md, checks/cloud/aws/ec2/no_public_egress_sgr.rego, checks/cloud/aws/ec2/no_public_egress_sgr_test.rego, checks/cloud/aws/ec2/no_public_ingress_acl.rego, checks/cloud/aws/ec2/no_public_ingress_sgr.rego, checks/cloud/azure/network/disable_rdp_from_internet.rego, checks/cloud/azure/network/no_public_egress.rego, checks/cloud/azure/network/no_public_egress_test.rego, checks/cloud/azure/network/no_public_ingress.rego, checks/cloud/azure/network/ssh_blocked_from_internet.rego, checks/cloud/digitalocean/compute/no_public_egress.rego, checks/cloud/digitalocean/compute/no_public_ingress.rego, checks/cloud/google/compute/no_public_egress.rego, checks/cloud/google/compute/no_public_egress_test.rego, checks/cloud/google/compute/no_public_ingress.rego, checks/cloud/nifcloud/computing/no_public_ingress_sgr.rego, checks/cloud/nifcloud/nas/no_public_ingress_nas_sgr.rego, checks/cloud/nifcloud/rdb/no_public_ingress_db_sgr.rego, checks/kubernetes/network/no_public_egress.rego, checks/kubernetes/network/no_public_ingress.rego, lib/cloud/net.rego
- https://github.com/aquasecurity/trivy/issues/8184
Checks that require restricting access to or from any IP address now check only this condition. In addition, the titles, descriptions, and messages for all such checks have been unified.
=> fix: align CIDR check rules with their title

.github/workflows/release.yaml
Fixes: https://github.com/aquasecurity/trivy-checks/actions/runs/12878785691/job/35905261053
`oras` is no longer included in the list of installed ubuntu 24 tools, so it must be installed manually.
=> fix(ci): setup oras

avd_docs/generic/general/AVD-KSV-0124/docs.md, checks/kubernetes/gatekeeper/repo_ambiguous_prefix.rego, checks/kubernetes/gatekeeper/repo_ambiguous_prefix_test.rego
Gatekeeper does a prefix-match (startswith) to check if a repo is allowed. this can be leveraged by attackers who create repos with simlar prefix which can bypass the prefix matching (see tests for examples)
related: https://github.com/open-policy-agent/gatekeeper-library/pull/616
=> feat: gatekeeper repo ambiguous prefix

.regal/config.yaml, .regal/rules/custom/regal/rules/custom/invalid-metadata/invalid_metadata.rego, .regal/rules/custom/regal/rules/custom/invalid-metadata/invalid_metadata_test.rego, Makefile, checks/cloud/aws/iam/no_policy_wildcards.rego, checks/docker/apt_get_missing_no_install_recommends.rego, checks/docker/apt_get_missing_yes_flag_to_avoid_manual_input.rego, checks/kubernetes/general/manage_namespace_secrets.rego, checks/kubernetes/general/manage_webhook_configurations.rego, checks/kubernetes/pss/baseline/6_apparmor_policy_disabled.rego
This PR adds an `invalid_metadata` rule to help maintain consistency, avoid errors, and enforce metadata standards.  This will help to avoid such mistakes: https://github.com/aquasecurity/trivy-checks/pull/327#discussion_r1929999968
=> ci: add lint for checks metadata

checks/docker/latest_tag.rego, checks/docker/latest_tag_test.rego
- https://github.com/aquasecurity/trivy/issues/8274
=> fix(checks): improve argument handling in AVD-DS-0001

.regal/rules/custom/regal/rules/custom/invalid-metadata/invalid_metadata.rego, .regal/rules/custom/regal/rules/custom/invalid-metadata/invalid_metadata_test.rego, avd_docs/kubernetes/general/AVD-KSV-0124/docs.md, checks/kubernetes/gatekeeper/repo_ambiguous_prefix.rego
Checks that do not use the input field are applied to all input data:
```bash
2025-01-30T02:59:21.0158634Z 2025-01-30T02:55:18Z	WARN	[rego] Module has no input selectors - it will be loaded for all inputs!	file_path="checks/kubernetes/gatekeeper/repo_ambiguous_prefix.rego" module="checks/kubernetes/gatekeeper/repo_ambiguous_prefix.rego"
```
=> lint: require input field of Rego metadata

.regal/rules/custom/regal/rules/custom/invalid-metadata/invalid_metadata.rego
Idea from https://github.com/aquasecurity/trivy-checks/pull/328#issuecomment-2622487260
=> lint: validate avd_id

Makefile, checks/kubernetes/advanced/default_namespace_should_not_be_used.rego, checks/kubernetes/advanced/default_namespace_should_not_be_used_test.rego
The `input.metadata.namespace` field may be missing, which may cause the check to fail.
=> fix: avoid reference to input.metadata.namespace

avd_docs/kubernetes/general/AVD-KSV-0123/docs.md, checks/kubernetes/general/masters_group_bind.rego
Currently, the metadata for AVD-KSV-0123 is the same as that for [AVD-KSV-01011](https://github.com/aquasecurity/trivy-checks/blob/dbc1975e8fa81ac30489c43cead6dda722615c3a/checks/kubernetes/gke/authenticate_group_bind.rego). Since AVD-KSV-0123 is related to the rule for the `system:masters` group, we will update it to the appropriate info.
=> chore: fix metadata for AVD-KSV-0123

checks/docker/latest_tag.rego, checks/docker/latest_tag_test.rego
- https://github.com/aquasecurity/trivy/issues/8438
```bash
Dockerfile (dockerfile)
Tests: 28 (SUCCESSES: 25, FAILURES: 3)
Failures: 3 (UNKNOWN: 0, LOW: 1, MEDIUM: 1, HIGH: 1, CRITICAL: 0)
AVD-DS-0001 (MEDIUM): Specify a tag in the 'FROM' statement for image ''
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
When using a 'FROM' statement you should use a specific tag to avoid uncontrolled behavior when the image is updated.
See https://avd.aquasec.com/misconfig/ds001
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Dockerfile:2
─────────────────────────────────────────────────────────────────────────────────────────── …
```
=> fix: DS001 should not trigger for an empty image

checks/cloud/aws/ec2/no_public_ingress_sgr_test.rego, lib/cloud/net.rego
Previously, protocol checks were case-sensitive, causing false positives. Now, all protocol values are normalized to lowercase before comparison. Additionally, numeric protocol values are converted to strings for consistency.
Related PRs:
- https://github.com/aquasecurity/trivy/issues/8460
=> fix(misconf): make protocol checks case-insensitive and convert numeric protocols to strings

.github/workflows/nightly-release.yaml, .github/workflows/release.yaml
Permissions must be granted to the called workflow.
Fix: https://github.com/aquasecurity/trivy-checks/actions/runs/13583124854
=> ci: grant permission to release workflow

checks/cloud/aws/documentdb/encryption_customer_key.rego, checks/cloud/aws/documentdb/encryption_customer_key_test.rego, test/rego/aws_document_db_test.go
- https://github.com/aquasecurity/trivy/issues/8530
=> fix: not to check DB instances in AVD-AWS-0022

avd_docs/kubernetes/general/AVD-KCV-0093/docs.md, checks/kubernetes/network/insecure_ingress_nginx.rego, checks/kubernetes/network/insecure_ingress_nginx.yaml, checks/kubernetes/network/insecure_ingress_nginx_test.rego
```bash
cat -n malicious-ingress.yaml
1	apiVersion: networking.k8s.io/v1
2	kind: Ingress
3	metadata:
4	  name: demo
5	  annotations:
6	    nginx.ingress.kubernetes.io/auth-url: "http://example.com/#;\ninjection_point"
7	    nginx.ingress.kubernetes.io/auth-tls-match-cn: "CN=invalid|cn"
8	    nginx.ingress.kubernetes.io/mirror-target: "http://example.com/#;\ninjection_point"
9	    nginx.ingress.kubernetes.io/mirror-host: "http://example.com/#;\ninjection_point"
10	spec:
11	  ingressClassName: nginx
12	  rules:
13	  - host: test.example.com
14	    http:
15	      paths:
16	      - path: /
17	        pathType: Prefix
18	        backend:
19	          service:
20	            name: test-service
21	            port:
22	              number: 80
```
```
$ trivy k8s --scanners=misconfig --report=all …
```
=> feat(checks): Add checks for `IngressNightmare`

cmd/bundle/bundle.sh
https://github.com/aquasecurity/trivy-checks/pull/308 missed adding the compliance specs to the bundle.
```shell
~/repos/trivy/trivy clean --checks-bundle
2025-03-27T23:30:06-06:00	INFO	Removing check bundle...
~/repos/trivy/trivy k8s --include-namespaces=default --checks-bundle-repository=localhost:5111/defsec:1  --scanners=misconfig --report=all  --severity=CRITICAL
2025-03-27T23:30:28-06:00	INFO	[misconfig] Need to update the checks bundle
2025-03-27T23:30:28-06:00	INFO	[misconfig] Downloading the checks bundle...
204.64 KiB / 204.64 KiB [-----------------------------------] 100.00% ? p/s 200ms
2025-03-27T23:30:30-06:00	INFO	Node scanning is enabled
2025-03-27T23:30:30-06:00	INFO	If you want to disable Node scanning via an in-cluster Job, please try '--disable-node-collector' to …
```
=> fix(bundle): Correctly add compliance checks into the bundle

.github/workflows/reusable-release.yaml
`Skitionek/notify-microsoft-teams` fixed the issue and now we can use it instead of the fork
See - https://github.com/aquasecurity/notify-microsoft-teams/pull/1
tested for Trivy-db - https://github.com/DmitriyLewen/trivy-db/actions/runs/14485778659/job/40630965075
=> ci: use `Skitionek/notify-microsoft-teams` instead of `aquasecurity` fork

avd_docs/aws/s3/AVD-AWS-0320/docs.md, checks/cloud/aws/s3/dns_compliant_name.rego
<https://docs.aws.amazon.com/AmazonS3/latest./dev/transfer-acceleration.html> is not found, whereas <https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html> is redirected to <https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html>.
=> Fix unreachable URL of AVD-AWS-0320 metadata

checks/cloud/aws/ecr/no_public_access.rego, checks/cloud/aws/s3/enable_logging.rego, checks/cloud/aws/sqs/no_wildcards_in_policy_documents.rego, checks/cloud/aws/sqs/no_wildcards_in_policy_documents_test.rego
From [doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_action.html):
> The prefix and the action name are case insensitive
- https://github.com/aquasecurity/trivy/issues/8879
=> fix: make wildcard match in IAM policy checks case-insensitive

Makefile
Enabling rules via a flag is not necessary, as this is already done via the config file. See https://docs.styra.com/regal#ignoring-all-rules-in-config
=> chore: remove unnecessary regal lint arguments

.regal/config.yaml, checks/kubernetes/insecure_ingress_nginx.rego, checks/kubernetes/insecure_ingress_nginx.yaml, lib/cloud/aws_s3.rego
This PR enables some rules from the `bugs` category for the linter that have not found issues or require minor fixes.
=> lint: enable some rules from bugs category

checks/cloud/aws/apigateway/no_public_access_test.rego, checks/cloud/aws/cloudfront/enforce_https_test.rego, checks/cloud/aws/dynamodb/table_customer_key_test.rego, checks/cloud/aws/iam/limit_s3_full_access_test.rego, checks/cloud/aws/kinesis/enable_in_transit_encryption_test.rego, checks/cloud/aws/rds/enable_cluster_deletion_protection_test.rego, checks/cloud/aws/rds/encrypt_instance_storage_data.rego, checks/cloud/aws/rds/encrypt_instance_storage_data_test.rego, checks/cloud/aws/s3/enable_logging_test.rego, checks/cloud/aws/s3/encryption_customer_key_test.rego, checks/cloud/aws/sqs/queue_encryption_with_cmk_test.rego, checks/cloud/azure/storage/allow_microsoft_service_bypass_test.rego, checks/cloud/google/compute/disable_allow_all_ports_firewall_rule.rego, checks/cloud/google/compute/disable_allow_all_ports_firewall_rule_test.rego, checks/cloud/google/compute/restrict_ssh_access.rego, checks/cloud/google/compute/restrict_ssh_access_test.rego, checks/cloud/google/compute/vm_disk_encryption_customer_key_test.rego, checks/cloud/google/iam/no_privileged_service_accounts.rego, checks/cloud/google/iam/no_user_granted_permissions.rego, checks/cloud/google/iam/no_user_granted_permissions_test.rego, checks/cloud/google/sql/encrypt_in_transit_data_test.rego, checks/cloud/nifcloud/network/http_not_used_test.rego, test/test_input_schema_test.go
This PR adds the `additionalProperties` property (set to `false`) to all Cloud objects in the schema, except for `iac.types.MapValue`, which is a map and is expected to accept arbitrary keys. This makes the validation stricter and helps catch unexpected fields in test inputs.
=> test: disallow extra fields in cloud schema validation

checks/cloud/google/storage/enable_bucket_logging.rego
The expression `not bucket.logging.logbucket.value` is true when the `value` field is missing, but by default Trivy fills the `logbucket` with empty values:
```json
"logging": {
...
"logbucket": {
"endline": 6,
"explicit": false,
"filepath": "main.tf",
"fskey": "fd569cbde7899a2c12c7fa8a4c51c3777becfc1797289d3e1c9e960fd56802a2",
"managed": true,
"resource": "google_storage_bucket.default",
"sourceprefix": "",
"startline": 1,
"unresolvable": false,
"value": ""
},
...
```
which is why this expression is never true:
```
| | Fail not bucket.logging.logbucket.value
```
Fixes:
https://github.com/aquasecurity/trivy-checks/actions/runs/16662841182/job/47163530682
=> fix(gcp): properly check if bucket has logging

cmd/bundle/bundle.sh, integration/check_examples_test.go
In one of the [PRs](https://github.com/aquasecurity/trivy-checks/actions/runs/16751450375/job/47422496831?pr=465), tests failed due to exceeding the maximum allowed errors during Rego compilation. This PR addresses the issue by skipping certain checks when creating the bundle, filtering them based on the minimal supported Trivy version. This is necessary to maintain compatibility with older Trivy versions that do not yet support such filtering.
Fixes: https://github.com/aquasecurity/trivy-checks/actions/runs/16751450375/job/47422496831?pr=465
=> test: skip unsupported checks for test bundles

checks/docker/update_instruction_alone.yaml, checks/docker/update_instruction_alone_test.rego, lib/docker/docker.rego
This PR improves shell command splitting using the `sh.parse_commands` function. The function is registered in OPA and safe to use starting from bundle version v1.*.
- https://github.com/aquasecurity/trivy/issues/9340
=> refactor: improve shell command splitting via sh.parse_commands

Makefile, integration/check_examples_test.go, integration/testcontainer/oras.go
Bitnami [has discontinued support](https://github.com/bitnami/containers#%EF%B8%8F-important-notice-upcoming-changes-to-the-bitnami-catalog) for several images. As a result, the `bitnami/oras` image on Docker Hub no longer has any available tags. It has now been replaced with `ghcr.io/oras-project/oras` from GHCR.
=> test: use ORAS image from GHCR

.github/dependabot.yml
Follow-up https://github.com/aquasecurity/trivy/pull/9475
=> ci: add 3-day cooldown for dependabot
