rules/cloud/policies/aws/dynamodb/table_customer_key_test.go

Fixed the tests after  https://github.com/aquasecurity/trivy-policies/pull/19

test: fix tests for AVD-AWS-0025

---

checks/kubernetes/pss/restricted/1_non_core_volume_types.rego
checks/kubernetes/pss/restricted/1_non_core_volume_types_test.rego

Fixes https://github.com/aquasecurity/trivy/discussions/5768

fix: csi is an allowed volume type

---

checks/kubernetes/aquacommercial/configmap_with_sensitive.rego

Configmap with sensitive data lacked iban and passport patterns. Added both.

Configmap with sensitive data lacks iban and passport patterns.

---

checks/kubernetes/general/file_system_not_read_only.rego

Fixes: https://github.com/aquasecurity/trivy/issues/5861

chore(checks): Bump AVD-KSV-0014 to HIGH

---

go.mod
go.sum

This PR improves wildcard checking in the following rules: AVD-AWS-0057, AVD-AWS-0114 and AVD-AWS-0120.

feat(aws): improve wildcard checking in policies

---

Makefile

3de4cf50f1 moved `rules/` to `checks/`

fix: Makefile: rules/ moved to checks/

---

checks/kubernetes/gke/authenticate_group_bind.rego

change system authenticate bind severity to low
- Related #65

fix: change system authenticate bind severity to low

---

checks/docker/prevent_sys_workdir_mount_test.rego
checks/docker/prevent_sys_workdir_mounts.rego

This PR adds a check to detect the [leaky vessels exploit](https://github.com/snyk/leaky-vessels-static-detector/) with Trivy.
Also fixes: https://github.com/aquasecurity/trivy-policies/issues/67
Signed-off-by: Simar <simar@linux.com>

feat(checks): Add check to detect Leaky Vessels exploit

---

avd_docs/azure/database/AVD-AZU-0027/Terraform.md
checks/cloud/azure/database/enable_audit.tf.go

Fixes https://github.com/aquasecurity/trivy/issues/5739

fix(azure): update remediation for AVD-AZU-0027

---

.github/workflows/verify-docs.yaml
avd_docs/aws/cloudfront/AVD-AWS-0013/Terraform.md
avd_docs/aws/cloudfront/AVD-AWS-0013/docs.md

Test run: https://github.com/aquasecurity/trivy-policies/actions/runs/8172406243/job/22342629575?pr=91

ci: add workflow to verify docs

---

checks/docker/update_instruction_alone.rego
checks/docker/update_instruction_alone_test.rego

Fixes https://github.com/aquasecurity/trivy/issues/6513

fix(rego): handle multiple install cmds in DS017

---

.gitignore
checks/docker/update_instruction_alone.rego
checks/docker/yum_clean_all_missing.rego
checks/docker/yum_clean_all_missing_test.rego
lib/docker/docker.rego

Fixes https://github.com/aquasecurity/trivy/issues/6776

fix(rego): improve AVD-DS-0015

---

avd_docs/kubernetes/general/AVD-KSV-0123/docs.md
checks/kubernetes/general/masters_group_bind.rego
checks/kubernetes/general/masters_group_bind_test.rego
commands/kubernetes/kubeletAnonymousAuthArgumentSet.yaml
commands/kubernetes/kubeletClientCaFileArgumentSet.yaml
commands/kubernetes/kubeletConfigYamlConfigurationFileOwnership.yaml
commands/kubernetes/kubeletConfigYamlConfigurationFilePermission.yaml
commands/kubernetes/kubeletMakeIptablesUtilChainsArgumentSet.yaml
commands/kubernetes/kubeletReadOnlyPortArgumentSet.yaml
commands/kubernetes/kubeletRotateCertificatesArgumentSet.yaml
commands/kubernetes/kubeletRotateKubeletServerCertificateArgumentSet.yaml
commands/kubernetes/kubeletServiceFileOwnership.yaml
commands/kubernetes/kubeletStreamingConnectionIdleTimeoutArgumentSet.yaml
specs/compliance/aws-eks-cis-1.4.yaml
specs/compliance/eks-cis-1.4.yaml

cis eks spec update
- Related https://github.com/aquasecurity/trivy/issues/6602

feat: cis eks spec update

---

pkg/specs/compliance/rke2-cis-1.24.yaml

fix: update rke2 spec title

---

checks/cloud/aws/ec2/no_excessive_port_access.go
checks/cloud/aws/ec2/no_excessive_port_access_test.go

Fixes https://github.com/aquasecurity/trivy/issues/7006

fix(checks): correctly check the protocol in the AVD-AWS-0102 rule

---

checks/cloud/aws/cloudfront/enable_waf.go
checks/cloud/aws/dynamodb/table_customer_key.rego
go.mod
test/rego_checks_test.go

This PR adds functional tests for already migrated checks from Go to Rego to prevent regression. The remaining tests will be added as the checks are moved.

test: init functional tests

---

test/rego/aws_access_analyzer_test.go
test/rego/aws_athena_test.go
test/rego/aws_cloudtrail_test.go
test/rego/aws_codebuild_test.go
test/rego/aws_config_test.go
test/rego/aws_document_db_test.go
test/rego/aws_dynamodb_test.go
test/rego/aws_s3_test.go
test/rego/azure_appservice_test.go
test/rego/azure_authorization_test.go
test/rego/azure_compute_test.go
test/rego/azure_container_test.go
test/rego/azure_database_test.go
test/rego/azure_datafactory_test.go
test/rego/azure_datalake_test.go
test/rego/azure_keyvault_test.go
test/rego/azure_monitor_test.go
test/rego/azure_network_test.go
test/rego/azure_securitycenter_test.go
test/rego/azure_synapse_test.go
test/rego/digitalocean_spaces_test.go
test/rego/github_test.go
test/rego/google_bigquery_test.go
test/rego/google_dns_test.go
test/rego/google_kms_test.go
test/rego/nifcloud_dns_test.go
test/rego/nifcloud_network_test.go
test/rego/nifcloud_sslcertificate_test.go
test/rego/oracle_test.go
test/rego/rego_checks_test.go

test: initialise tests in each test file

---

scripts/verify-bundle.go

This PR adds automatic pulling of Trivy images

chore: always pull trivy images

---

go.mod
go.sum
test/rego/rego_checks_test.go

Related PRs: 
- https://github.com/aquasecurity/trivy/pull/7420

chore(deps): Bump trivy version

---

avd_docs/google/sql/AVD-GCP-0015/Terraform.md
checks/cloud/google/sql/encrypt_in_transit_data.rego
checks/cloud/google/sql/encrypt_in_transit_data.tf.go
checks/cloud/google/sql/encrypt_in_transit_data_test.rego

Close: https://github.com/aquasecurity/trivy/issues/7565

feat(checks): add ssl_mode support in AVD-GCP-0015

---

checks/cloud/aws/rds/enable_cluster_deletion_protection.rego
checks/cloud/aws/rds/enable_cluster_deletion_protection_test.rego

- https://github.com/aquasecurity/trivy/issues/7899

fix(checks): check only clusters in AVD-AWS-0343

---

avd_docs/google/gke/AVD-GCP-0057/Terraform.md
checks/cloud/aws/elb/alb_not_public.rego
checks/cloud/aws/elb/drop_invalid_headers.rego
checks/cloud/aws/lambda/enable_tracing.rego
checks/cloud/google/gke/enable_auto_repair.rego
checks/cloud/google/gke/enable_auto_upgrade.rego
checks/cloud/google/gke/enable_ip_aliasing.rego
checks/cloud/google/gke/enable_master_networks.rego
checks/cloud/google/gke/enable_private_cluster.rego
checks/cloud/google/gke/enable_stackdriver_logging.rego
checks/cloud/google/gke/enable_stackdriver_monitoring.rego
checks/cloud/google/gke/metadata_endpoints_disabled.rego
checks/cloud/google/gke/no_legacy_authentication.rego
checks/cloud/google/gke/node_metadata_security.rego
checks/cloud/google/gke/node_metadata_security.yaml
checks/cloud/google/gke/node_pool_uses_cos.rego
checks/cloud/google/gke/node_shielding_enabled.rego
checks/cloud/google/gke/use_cluster_labels.rego
checks/cloud/google/gke/use_rbac_permissions.rego
checks/cloud/google/gke/use_service_account.rego

This PR does the same thing as https://github.com/aquasecurity/trivy-checks/pull/298 but for all remaining resources
- https://github.com/aquasecurity/trivy/issues/8054

fix: do not check unmanaged resources

---

checks/docker/run_apt_get_dist_upgrade.rego
test/docker_test.go
test/kubernetes_test.go

Closes: https://github.com/aquasecurity/trivy/issues/8017

refactor(checks): Deprecate AVD-DS-0024

---

checks/docker/missing_apk_no_cache.rego
checks/docker/missing_apk_no_cache_test.rego
lib/docker/cmdutil.rego
lib/docker/cmdutil_test.rego

Related issue:
- https://github.com/aquasecurity/trivy/issues/8268

fix(checks): check no-cache flag only with add command in DS025

---

.github/workflows/canary.yaml
.github/workflows/integration-tests.yaml
.github/workflows/nightly-release.yaml
.github/workflows/outdated-api-update.yaml
.github/workflows/release.yaml
.github/workflows/reusable-release.yaml
.github/workflows/test-bundle.yml
.github/workflows/test-go.yaml
.github/workflows/test-rego.yaml
.github/workflows/verify-docs.yaml
scripts/bundle.sh

- https://github.com/aquasecurity/trivy/issues/7030
Successful runs:
- Nightly release: https://github.com/nikpivkin/trivy-checks/actions/runs/13567087291
- Release: https://github.com/nikpivkin/trivy-checks/actions/runs/13567251820

ci: add nightly release workflow for automated builds

---

checks/cloud/aws/elasticsearch/use_secure_tls_policy.rego
checks/cloud/aws/elasticsearch/use_secure_tls_policy_test.rego

- https://github.com/aquasecurity/trivy/issues/8551

feat: support Policy-Min-TLS-1-2-PFS-2023-10 in AVD-AWS-0126

---

avd_docs/kubernetes/general/AVD-KSV-0039/docs.md
avd_docs/kubernetes/general/AVD-KSV-0040/docs.md
checks/kubernetes/resources/use_limit_range.rego
checks/kubernetes/resources/use_limit_range_test.rego
checks/kubernetes/resources/use_resource_quota.rego
checks/kubernetes/resources/use_resource_quota_test.rego

This PR adds `kind` to the input selectors, and updates the descriptions and messages of the checks.
- https://github.com/aquasecurity/trivy/issues/8635

fix: add kind to input selector in KSV039 and KSV040

---

checks/cloud/aws/ec2/add_description_to_security_group.rego
checks/cloud/aws/ec2/add_description_to_security_group_test.rego

- https://github.com/aquasecurity/trivy/issues/8665

fix: do not check default security group in AVD-AWS-0099

---

avd_docs/google/gke/AVD-GCP-0048/Terraform.md
checks/cloud/google/gke/metadata_endpoints_disabled.rego
checks/cloud/google/gke/metadata_endpoints_disabled.yaml
checks/cloud/google/gke/metadata_endpoints_disabled_test.rego

- https://github.com/aquasecurity/trivy/issues/8701

fix: skip GKE Autopilot clusters in AVD-GCP-0048

---

avd_docs/kubernetes/general/AVD-KSV-0037/docs.md
checks/kubernetes/security/protect_core_components_namespace.rego

Fixes: https://github.com/aquasecurity/trivy/issues/8691

fix(checks): Update description of KSV037

---

checks/kubernetes/security/9_unsafe_sysctl_options_set.rego

Related issue:
- https://github.com/aquasecurity/trivy/issues/8739

feat: add support for new allowed sysctls in AVD-KSV-0026

---

checks/kubernetes/security/9_unsafe_sysctl_options_set.rego
checks/kubernetes/security/9_unsafe_sysctl_options_set_test.rego

Related PRs:
- https://github.com/aquasecurity/trivy-checks/pull/388

feat: consider k8s version in sysctls checks in KSV026

---

CONTRIBUTING.md

Follow-up: b28eeb7b8997c955e132b9217b8f54a1c1cfb14d

Fix filename in CONTRIBUTING.md

---

.regal/config.yaml
checks/kubernetes/any_verb_test.rego
checks/kubernetes/kubelet_https.rego
checks/kubernetes/peer_client_cert_auth.rego

https://docs.styra.com/regal/rules/bugs/duplicate-rule

lint: enable 'duplicate-rule' rule

---

avd_docs/aws/s3/AVD-AWS-0132/CloudFormation.md
avd_docs/aws/s3/AVD-AWS-0132/Terraform.md
avd_docs/aws/s3/AVD-AWS-0132/docs.md
checks/cloud/aws/s3/encryption_customer_key.rego
checks/cloud/aws/s3/encryption_customer_key.yaml

Related issue: https://github.com/aquasecurity/trivy/issues/8954

docs: improve documentation and examples for AVD-AWS-0132

---

checks/cloud/azure/storage/queue_services_logging_enabled.rego

Since ARM templates do not support queue properties configuration, unlike Terraform, we should consider whether this value is managed to avoid false positives. The property lookup was performed in [this repository](https://github.com/Azure/azure-resource-manager-schemas).

fix: check if queue properties is managed in AVD-AZU-0009

---

avd_docs/google/gke/AVD-GCP-0050/Terraform.md
checks/cloud/google/gke/use_service_account.rego
checks/cloud/google/gke/use_service_account.yaml
checks/cloud/google/gke/use_service_account_test.rego
integration/check_examples_test.go

- https://github.com/aquasecurity/trivy/issues/9038

feat: detect default SA usage in GKE Autopilot/NAP in AVD-GCP-0050

---

cmd/avd_generator/main.go
integration/check_examples_test.go
internal/examples/examples.go
pkg/rego/metadata/load.go
pkg/rego/metadata/load_test.go
pkg/rego/metadata/metadata.go
test/rules_test.go

This PR adds additional data to the metadata that can be used, for example, in avd-generator.

chore: store additional info in metadata
